/* The only file most installations need to edit. Times are deliberately broad. */
var CONFIG = Object.freeze({
  /* Bump this value whenever replacing an asset without changing its filename. */
  assetVersion: '2026-09-03-2',
  videoRoot: 'assets/video/',
  videoFiles: Object.freeze({
    adjust: 'Adjust.mp4',
    blink: 'Blink.mp4',
    doubleBlink: 'DoubleBlink.mp4',
    flightAway: 'Away.mp4',
    flightReturn: 'Return.mp4',
    lightning: 'Lightning.mp4',
    mausoleum: 'Mausoleum.mp4',
    lookLeft: 'LookLeft.mp4',
    lookViewer: 'LookViewer.mp4',
    preen: 'Preen.mp4',
    ruffle: 'Ruffle.mp4',
    settle: 'Settle.mp4',
    wingStretch: 'Stretch.mp4'
  }),
  mausoleumSound: 'assets/audio/Raven Animation – Mausoleum.mp4',
  /* Optional licensed thunder file. Null uses the built-in Web Audio thunder. */
  lightningSound: null,
  lightningThunderDelayRatio: 0.16,
  lightningThunderVolume: 0.16,
  blinkMinSeconds: 20,
  blinkMaxSeconds: 120,
  doubleBlinkChance: 0.12,
  adjustMinMinutes: 5,
  adjustMaxMinutes: 18,
  ruffleMinMinutes: 4,
  ruffleMaxMinutes: 20,
  settleMinMinutes: 3,
  settleMaxMinutes: 14,
  preenMinMinutes: 15,
  preenMaxMinutes: 45,
  wingStretchMinMinutes: 30,
  wingStretchMaxMinutes: 60,
  headMoveMinMinutes: 10,
  headMoveMaxMinutes: 40,
  flightAwayMinHours: 2,
  flightAwayMaxHours: 4,
  flightReturnMinSeconds: 30,
  flightReturnMaxSeconds: 180,
  /* First frame in Flight Away where the raven has completely cleared view. */
  flightAwayCleanFrameSeconds: 44.45,
  longQuietChance: 0.12,
  longQuietMultiplier: 1.8,
  videoVolume: 0.22,
  debug: false
});
